/**
 * Generated by tsnapi — public API snapshot of `dirclone` */
// Interfaces
export interface Options {
  root?: string;
  output?: string;
  yes?: boolean;
  url?: string;
}

// Types
export type ResolvedOptions = Required<Options>;

// Functions
export declare function create(_: string | undefined, _: Options): Promise<void>;
export declare function parseDir(_: string): string;
export declare function resolveOptions(_: Options): Promise<ResolvedOptions>;